### ISSUE TITLE
Do upgradable reads block plain reads?

### ISSUE THREAD

**Issue by matklad** [Amanieu/parking_lot#101] opened 2018-10-30 14:24 UTC
Hi! I see a behavior which I think does not match the docs, so either the docs are unclear, or there's a bug.

Here's the code that shows the behavior:

https://github.com/matklad/parking-lot-deadlock/blob/95989b3da40ed42e1ed7acba829d20b8b4319845/src/main.rs

If I run the code on my machine (linux, x86_64), I get a deadlock after a couple of hundred iterations.

I would expect that this program never deadlocks though, because, from my reading of the `upgradable_read` docs it follows that a `read` can never be blocked by a not-upgraded upgradable_read.

**Comment by Amanieu** [comment] 2018-10-30 20:14
I reproduced it with 2 threads upgrading. So what seems to have happened is this:
1. Thread A acquires and upgradable lock.
2. Thread B tries to acquire an upgradable lock, and blocks. This is normal since you can only have 1 upgradable lock at any time.
3. Thread C tries to acquire a read lock, and blocks because there is already another thread blocked waiting for a lock.

**Comment by matklad** [comment] 2018-10-30 20:15
@Amanieu and `3` is a bug, right?

**Comment by Amanieu** [comment] 2018-10-30 20:21
... probably. The rwlock was originally written as a task-fair rwlock, where a reader will block if there is an existing writer blocked on it. This helps prevent writer starvation. The problem is that this code was not revisited when upgradable locks were implemented.

**Comment by nikomatsakis** [comment] 2018-10-30 20:32
Well I suppose that there is no problem so long as Thread 1 doesn't wind up blocked on Thread 3, right @Amanieu ?

**Comment by nikomatsakis** [comment] 2018-10-30 20:32
I opened https://github.com/salsa-rs/salsa/pull/75 but maybe it is not necessary

**Comment by matklad** [comment] 2018-12-27 13:03
Here's a slight variation of the deadlock:

https://github.com/matklad/parking-lot-deadlock/commit/12945a9909f2969001449e5034abb686a3c8c2c1

Here, threads repeatedly upgrade_read/write/read the lock. What is interesting is that writers and upgraders deadlock against each other, without busy-waiting which was used in the first example.

**Comment by matklad** [comment] 2018-12-27 13:11
Note that samples use parking-lot `0.6.*`. I've checked the last one with `0.7.0`, and it still deadlocks.

**Comment by Amanieu** [comment] 2019-01-01 14:11
Ugh, upgradable locks are a pain to get right...

@matklad 

Your new deadlock is an actual bug, which should be fixed by 5977113b42f041bc0ba0c1bacea6296a5588b92f.

The first one is more of a design flaw in the current rwlock implementation, where an upgradable read can in some cases block a normal read.

**Comment by Amanieu** [comment] 2019-01-01 14:31
Also, fun fact, the bug is in the unlock path for normal reads. If you remove the assert from your example then the bug doesn't trigger.

**Comment by matklad** [comment] 2019-01-01 14:36
>Also, fun fact, the bug is in the unlock path for normal reads. If you remove the assert from your example then the bug doesn't trigger.

Yeah, I've noticed that, that's why assert is in there! Should have added this bit of info to the original comment.

Looks like salsa + rust-analyzer combo is a good stress test for parking log! :)

**Closed** 2019-01-31 15:40 UTC
