### ISSUE TITLE
Poison detection

### ISSUE THREAD

**Issue by arthurprs** [Amanieu/parking_lot#44] opened 2017-10-21 07:17 UTC
Poison detection can be very useful, especially for debug builds.

One possible implementation can share the backend already in place for deadlock detection (w/ minor modifications).

Something along those lines could work:
1. Check if the thread is panicking on each guard drop()
2a. If so, register it in the wait graph (ex: mutex A waits for mutex A).
2b. If so, leave the mutex/rwlock locked (not required I think)
3. Modify the cycle detection to account for such cases

Naturally, calling `std::thread::panicking` is probably not super cheap so this must go behind a feature flag as well.

**Comment by Amanieu** [comment] 2017-11-16 06:27
I'm not really a fan of poison detection. Generally the intended behavior on panic is to simply release any locks while unwinding. If you add poison detection then you would need a method to explicitly un-poison a mutex so that it is usable again.

**Comment by arthurprs** [comment] 2017-11-17 13:30
I understand your point. I have yet to see real programs that handle panicking gratefully enough to just reuse locks after the panic.

I fell that rust ecosystem leans towards `panics are bad, real bad`, the existence of the exit on panic also points to that.

**Comment by mitsuhiko** [comment] 2018-02-15 04:36
I have seen more rust code that continues to function after panicking thn rust code that does not handle poisoning at all. Most code just unwraps.

**Comment by arthurprs** [comment] 2018-02-15 10:29
If unwrap() is the most common usage (I agree, btw), does that mean people expect a poisoned lock to just panic on the next access?

**Comment by mitsuhiko** [comment] 2018-02-15 10:36
@arthurprs with std locks it will panic. Yes. If that's what people expect I don't know. I never quite cared about lock poisoning which is why I use parking_lot exclusively and I have not yet encountered any issues with that and I have a lot of cases where a lock is held when it panics (i set up landing pads for cffi boundaries and out of bound errors and others usually panic). Never had an issue where a process would corrupt.

**Comment by Amanieu** [comment] 2018-02-16 18:02
I'm going to close this. I won't be adding poisoning support to parking_lot.

**Closed by Amanieu** 2018-02-16 18:02 UTC
